apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: postgres
  name: postgres
spec:
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backblaze
  bootstrap:
    initdb:
      database: drum
      owner: drum
      secret:
        name: postgres-user
  instances: 2
  monitoring:
    enablePodMonitor: true
  resources:
    limits:
      cpu: 400m
      memory: 420Mi
    requests:
      cpu: 100m
      memory: 256Mi
  storage:
    size: 1Gi
    storageClass: lvm-thin
  superuserSecret:
    name: postgres-admin
