apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: backblaze
  namespace: mended-drum
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: postgres
    meta.helm.sh/release-namespace: mended-drum
    kustomize.toolkit.fluxcd.io/prune: disabled
    helm.sh/resource-policy: keep
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://minio-ankhmorpork-thaum-xyz/postgres/mended-drum
    endpointURL: https://s3.eu-central-003.backblazeb2.com
    s3Credentials:
      accessKeyId:
        key: S3_ACCESS_KEY
        name: postgres-backup
      secretAccessKey:
        key: S3_SECRET_KEY
        name: postgres-backup
    wal:
      compression: gzip
