---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc
  namespace: longhorn-system
spec:
  plugin:
    # Key must match experimental.plugins in the traefik values, not the module name.
    oidc:
      Secret: "urn:k8s:secret:oidc-secret:pluginSecret"
      Provider:
        Url: "https://login.krupa.net.pl"
        ClientId: "urn:k8s:secret:oidc-secret:providerClientId"
        ClientSecret: "urn:k8s:secret:oidc-secret:providerClientSecret"
