apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Namespace is created and owned by the parent.
namespace: datalake-alerts
resources:
  - serviceaccount.yaml
  - externalsecret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
