apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: alertmanager-webhook-receiver
    app.kubernetes.io/name: github-receiver
  name: github-receiver
