apiVersion: homer.bananaops.io/v1alpha1
kind: HomerServices
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  groups:
    - name: Ankh Cloud
      icon: "fa fa-cloud"
      items:
        - name: Stirling PDF
          url: "https://pdf.krupa.net.pl"
          subtitle: "PDF manipulation tool"
          logo: "https://cdn.jsdelivr.net/npm/@loganmarchione/homelab-svg-assets@latest/assets/stirlingpdf.svg"
