apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alertmanager
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap-template.yaml
  - externalsecret.yaml
  - alertmanager.yaml
  - service.yaml
  - servicemonitor.yaml
  - poddisruptionbudget.yaml
  - ingress.yaml
  - prometheusrule.yaml
  - grafana-datasource-cm.yaml
  - github-receiver/
