apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: backblaze-sonarr
  namespace: multimedia
spec:
  retentionPolicy: 7d
  configuration:
    destinationPath: s3://minio-ankhmorpork-thaum-xyz/postgres/sonarr
    endpointURL: https://s3.eu-central-003.backblazeb2.com
    s3Credentials:
      accessKeyId:
        key: S3_ACCESS_KEY
        name: postgres-sonarr-backup
      secretAccessKey:
        key: S3_SECRET_KEY
        name: postgres-sonarr-backup
    wal:
      compression: gzip
