apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/part-of: sonarr
    app.kubernetes.io/version: 4.0.19
  name: sonarr
spec:
  ports:
    - name: http
      port: 8989
      protocol: TCP
      targetPort: http
    - name: metrics
      port: 9707
      protocol: TCP
      targetPort: metrics
  selector:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: sonarr
      app.kubernetes.io/part-of: sonarr
  sessionAffinity: None
  type: ClusterIP
