apiVersion: homer.bananaops.io/v1alpha1
kind: HomerServices
metadata:
  name: changedetection
spec:
  groups:
    - name: Ankh Cloud
      icon: "fa fa-cloud"
      items:
        - name: Change Detection
          url: "https://change.krupa.net.pl"
          subtitle: "Website change detection"
          logo: "https://user-images.githubusercontent.com/275001/231676626-7d768df9-be4c-4187-a573-aba640b826d3.svg"
