apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - oidc-secret.yaml
  - cookie-generator.yaml
  - cookie-secret.yaml
  - ingress.yaml
  - ingress-cloudflare.yaml
  - homerservice.yaml
