apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: changedetection-oauth2-cookie
spec:
  refreshInterval: "0"
  target:
    name: changedetection-oauth2-cookie
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: changedetection-oauth2-cookie
