database: drum
owner: drum

cluster:
  instances: 2
  storage:
    size: 1Gi
  resources:
    limits:
      cpu: 400m
      memory: 420Mi
    requests:
      cpu: 100m
      memory: 256Mi

backup:
  schedule: "0 30 23 * * *"
  objectStore:
    name: versity
    retentionPolicy: 30d
    pathSuffix: mended-drum
    bucketPrefix: s3://cnpg/postgres
    endpointURL: http://versitygw.cnpg-system.svc.cluster.local:7070

externalSecrets:
  admin:
    remoteKey: MENDED_DRUM_DB_ADMIN_PASS
  user:
    remoteKey: MENDED_DRUM_DB_PASS
