apiVersion: homer.bananaops.io/v1alpha1
kind: HomerServices
metadata:
  name: pyrra
  namespace: monitoring
spec:
  groups:
    - name: Administration
      icon: "fa fa-user-shield"
      items:
        - name: Pyrra
          url: "https://pyrra.ankhmorpork.thaum.xyz"
          logo: "https://avatars.githubusercontent.com/u/87393422?s=200&v=4"
