apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - release.yaml
  - pg-connection.yaml
  - encryption-key.yaml
  - podmonitor.yaml
  - ingress-cloudflare.yaml
  - slo-probe-success.yaml
configMapGenerator:
  - name: values-pocket-id
    files:
      - values.yaml=values.yaml
