apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: thaum-rules
  namespace: monitoring
spec:
  groups:
    - name: scrape-health.rules
      rules:
        - alert: ExporterTargetDown
          annotations:
            description: Exporter {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) reported its target being down. This results in lack of ability to scrape metrics from the main service.
            summary: Service monitored by exporter is Down
          expr: '{__name__=~".*_up",__name__!="node_network_up",__name__!="node_supervisord_up"} == 0'
          for: 5m
          labels:
            severity: warning
