apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-oidc
  labels:
    app.kubernetes.io/name: open-webui
spec:
  data:
    - remoteRef:
        key: MENDED_DRUM_OIDC_CLIENT_ID
      secretKey: OAUTH_CLIENT_ID
    - remoteRef:
        key: MENDED_DRUM_OIDC_CLIENT_SECRET
      secretKey: OAUTH_CLIENT_SECRET
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: open-webui-oidc
