apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
  labels:
    app.kubernetes.io/name: litellm
spec:
  data:
    - remoteRef:
        key: AI_GATEWAY_ANTHROPIC_KEY
      secretKey: ANTHROPIC_API_KEY
    - remoteRef:
        key: AI_GATEWAY_LITELLM_MASTER_KEY
      secretKey: PROXY_MASTER_KEY
    - remoteRef:
        key: AI_GATEWAY_OIDC_CLIENT_ID
      secretKey: GENERIC_CLIENT_ID
    - remoteRef:
        key: AI_GATEWAY_OIDC_CLIENT_SECRET
      secretKey: GENERIC_CLIENT_SECRET
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: litellm-secrets
