apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-security
resources:
  - repository.yaml
  - release.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: values-kyverno
    files:
      - values.yaml=values.yaml
