apiVersion: v1
kind: Namespace
metadata:
  name: ups
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    flux.rbac.thaum.xyz/role: cluster-admin
    pod-security.kubernetes.io/enforce: baseline
