apiVersion: v1
kind: Namespace
metadata:
  name: nanny-ogg
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    flux.rbac.thaum.xyz/role: cluster-admin
    group.rbac.thaum.xyz/nanny-ogg: edit
    pod-security.kubernetes.io/enforce: baseline
