apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
  name: prometheus-grafana-datasource
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        orgId: 1
        uid: datalake-metrics
        url: http://prometheus-k8s.datalake-metrics.svc:9090
        access: proxy
        isDefault: true
