apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Namespace is created and owned by the parent.
namespace: datalake-metrics
resources:
  - serviceaccount.yaml
  - serviceaccount-token.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - role-config.yaml
  - rolebinding-config.yaml
  - prometheus.yaml
  - service.yaml
  - servicemonitor.yaml
  - poddisruptionbudget.yaml
  - ingress.yaml
  - prometheusrule.yaml
  - grafana-datasource-cm.yaml
