apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceAccount.yaml
  - service.yaml
  - service-node.yaml
  - ingress.yaml
  - statefulset.yaml
  - middleware-no-x-frowarded-for.yaml
