# ClusterIP on purpose: this is only the ingress backend. External clients reach
# plex through the LoadBalancer in service-lb.yaml.
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: plex
    app.kubernetes.io/part-of: plex
  name: plex
spec:
  ports:
    - name: plex
      port: 32400
      protocol: TCP
      targetPort: plex
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: plex
    app.kubernetes.io/part-of: plex
