apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - release.yaml
  - credentials.yaml
  - metrics-credentials.yaml
  - servicemonitor.yaml
  - ingress-cloudflare.yaml
  - slo-probe-success.yaml
configMapGenerator:
  - name: values-litellm
    files:
      - values.yaml=values.yaml
