apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - credentials.yaml
  - db-credentials.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - ingress-cloudflare.yaml
