#!/usr/bin/env python3
"""Generate the reference pages that are derivable from the manifests.

Reference rots faster than anything else on the docs site and benefits least
from prose, so the parts that are mechanically derivable are generated here and
checked in CI rather than typed. Everything this writes is overwritten on every
run -- edit this script, not the output.

Reads git-tracked manifests only, the same as hack/validate-manifests.sh, so a
new app is invisible until staged.
"""

import pathlib
import subprocess
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs" / "reference"
BANNER = (
    "<!-- Generated by hack/generate-docs-reference.py. Do not edit by hand;\n"
    "     run `make docs-reference` instead. -->\n"
)


def tracked(prefix):
    out = subprocess.run(
        ["git", "-C", str(ROOT), "ls-files", prefix],
        capture_output=True, text=True, check=True,
    ).stdout.split()
    return [ROOT / p for p in out]


def load_all(path):
    try:
        return [d for d in yaml.safe_load_all(path.read_text()) if isinstance(d, dict)]
    except yaml.YAMLError:
        return []


def apps():
    """One row per directory under k8s/apps.

    Enumerated by directory, not by root kustomization.yaml: homer, paperless and
    dlna-local have none, because their Flux Kustomizations point at
    subdirectories instead.
    """
    files = [f for f in tracked("k8s/apps") if f.suffix in (".yaml", ".yml")]
    by_app = {}
    for f in files:
        parts = f.relative_to(ROOT).parts
        if len(parts) < 4:
            continue
        by_app.setdefault(parts[2], []).append(f)

    flux = []
    for p in tracked("k8s/flux/apps"):
        for d in load_all(p):
            path = d.get("spec", {}).get("path", "").rstrip("/")
            if path:
                flux.append((p.stem, path))

    rows = []
    for app in sorted(by_app):
        ns, ingresses = None, []
        for f in sorted(by_app[app]):
            for d in load_all(f):
                if d.get("kind") == "Namespace" and not ns:
                    ns = d.get("metadata", {}).get("name")
                if d.get("namespace") and not ns:
                    ns = d["namespace"]
                if d.get("kind") == "Ingress":
                    cls = d.get("spec", {}).get("ingressClassName", "?")
                    for rule in d.get("spec", {}).get("rules", []) or []:
                        if rule.get("host"):
                            ingresses.append((rule["host"], cls))
        owners = sorted(
            {name for name, path in flux
             if path == f"./k8s/apps/{app}" or path.startswith(f"./k8s/apps/{app}/")}
        )
        rows.append((app, ns, owners, sorted(set(ingresses))))
    return rows


def write_apps(rows):
    out = [BANNER, "# Applications { .quad-reference }\n\n"]
    out.append(
        "Every application under `k8s/apps/`, the namespace it renders into, the Flux\n"
        "Kustomization that applies it, and the hostnames it answers on.\n"
    )
    out.append(
        "\n!!! note\n\n"
        "    Hostnames are read from Ingress **manifests**. An Ingress rendered by a\n"
        "    Helm chart from `values.yaml` does not appear here, so an app with no\n"
        "    hostname listed is not necessarily unreachable.\n"
    )
    out.append("\n| App | Namespace | Flux Kustomization | Hostnames |")
    out.append("\n| --- | --- | --- | --- |\n")
    for app, ns, flux, ing in rows:
        hosts = (
            "<br>".join(f"`{h}` ({c})" for h, c in ing) if ing else "—"
        )
        out.append(
            f"| `{app}` | `{ns or '—'}` | "
            f"{', '.join(f'`{f}`' for f in flux) or '**none**'} | {hosts} |\n"
        )
    out.append(f"\n{len(rows)} applications.\n")
    (DOCS / "apps.md").write_text("".join(out))


def policies():
    rows = []
    for f in sorted(tracked("k8s/platform/security/kyverno/policies/*.yaml")):
        for d in load_all(f):
            kind = d.get("kind", "")
            if not kind.endswith("Policy"):
                continue
            spec = d.get("spec", {})
            res = sorted(
                {
                    r
                    for rule in spec.get("matchConstraints", {}).get("resourceRules", [])
                    for r in rule.get("resources", [])
                }
            )
            actions = spec.get("validationActions") or []
            msgs = [
                " ".join(str(v.get("message", "")).split())
                for v in spec.get("validations", [])
            ]
            rows.append(
                {
                    "name": d["metadata"]["name"],
                    "kind": kind,
                    "resources": res,
                    "actions": actions,
                    "messages": [m for m in msgs if m],
                    "file": str(f.relative_to(ROOT)),
                }
            )
    return rows


def write_policies(rows):
    out = [BANNER, "# Admission policies { .quad-reference }\n\n"]
    out.append(
        "Kyverno policies applied to every request. **Deny** blocks the apply;\n"
        "**Warn** records an audit warning and lets it through, so a warn-only rule\n"
        "is invisible until something goes wrong.\n"
    )
    out.append("\n| Policy | Applies to | Effect |")
    out.append("\n| --- | --- | --- |\n")
    for r in rows:
        eff = ", ".join(r["actions"]) or ("mutates" if r["kind"].startswith("Mutating") else "—")
        res = ", ".join(f"`{x}`" for x in r["resources"]) or "—"
        anchor = r["name"].replace(".", "")
        out.append(f"| [`{r['name']}`](#{anchor}) | {res} | **{eff}** |\n")
    for r in rows:
        out.append(f"\n## `{r['name']}`\n\n")
        eff = ", ".join(r["actions"]) or ("mutates matching resources" if r["kind"].startswith("Mutating") else "—")
        out.append(
            f"`{r['kind']}` on {', '.join(f'`{x}`' for x in r['resources']) or '—'} — "
            f"**{eff}**. Source: [`{r['file']}`](https://github.com/thaum-xyz/ankhmorpork/blob/master/{r['file']}).\n"
        )
        if r["messages"]:
            out.append("\nRules enforced:\n\n")
            for m in r["messages"]:
                out.append(f"- {m}\n")
    (DOCS / "admission-policies.md").write_text("".join(out))


def main():
    if not DOCS.is_dir():
        sys.exit(f"{DOCS} does not exist")
    rows = apps()
    write_apps(rows)
    pol = policies()
    write_policies(pol)
    print(f"wrote apps.md ({len(rows)} apps) and admission-policies.md ({len(pol)} policies)")


if __name__ == "__main__":
    main()
