#!/usr/bin/env python3
"""Generate the reference pages that are derivable from the manifests.

Reference rots faster than anything else on the docs site and benefits least
from prose, so the parts that are mechanically derivable are generated here and
checked in CI rather than typed. Everything this writes is overwritten on every
run -- edit this script, not the output.

Whole pages written:

  docs/reference/apps.md                 every app, namespace, Kustomization, hosts
  docs/reference/admission-policies.md   every Kyverno policy anywhere under k8s/
  docs/reference/flux-kustomizations.md  every Flux Kustomization: layer, path,
                                         interval, prune, wait, dependsOn
  docs/reference/helm-releases.md        every HelmRelease: chart, source, interval,
                                         where its values come from

Blocks written into otherwise hand-written pages, between
`<!-- generated:NAME -->` and `<!-- /generated:NAME -->` markers:

  docs/reference/ingress.md   ingress-classes, cluster-issuers, external-dns

Chart *versions* are deliberately not written anywhere here. Renovate bumps them
in the manifests several times a week, and a generated page that carried them
would need regenerating in every one of those PRs. The manifest is the version's
home; these pages link to it.

Reads git-tracked manifests only, the same as hack/validate-manifests.sh, so a
new file is invisible until staged.
"""

import pathlib
import re
import subprocess
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs" / "reference"
REPO = "https://github.com/thaum-xyz/ankhmorpork"
BANNER = (
    "<!-- Generated by hack/generate-docs-reference.py. Do not edit by hand;\n"
    "     run `make docs-reference` instead. -->\n"
)


# --- helpers -----------------------------------------------------------------


def tracked(prefix):
    out = subprocess.run(
        ["git", "-C", str(ROOT), "ls-files", prefix],
        capture_output=True, text=True, check=True,
    ).stdout.split()
    return [ROOT / p for p in out]


def yaml_files(prefix):
    return [f for f in tracked(prefix) if f.suffix in (".yaml", ".yml")]


def load_all(path):
    try:
        return [d for d in yaml.safe_load_all(path.read_text()) if isinstance(d, dict)]
    except yaml.YAMLError:
        return []


def is_k8s_object(doc):
    return "apiVersion" in doc and "kind" in doc


def rel(path):
    return str(path.relative_to(ROOT))


def blob(path):
    """Markdown link to the file on GitHub, labelled with its repo-relative path."""
    r = rel(path)
    return f"[`{r}`]({REPO}/blob/master/{r})"


def tree(repo_path):
    """Markdown link to a directory on GitHub. Accepts Flux-style ./k8s/... paths."""
    p = repo_path.lstrip("./")
    return f"[`{p}`]({REPO}/tree/master/{p})"


def code_list(items, empty="—"):
    return ", ".join(f"`{x}`" for x in items) if items else empty


def write_block(path, name, body):
    """Replace the content between the generated:NAME markers in a hand-written page."""
    text = path.read_text()
    start, end = f"<!-- generated:{name} -->", f"<!-- /generated:{name} -->"
    if start not in text or end not in text:
        sys.exit(f"{rel(path)}: missing markers for generated block {name!r}")
    head, rest = text.split(start, 1)
    _, tail = rest.split(end, 1)
    note = (
        "<!-- This block is written by hack/generate-docs-reference.py; edit the\n"
        "     manifests it reads, not the table. -->\n"
    )
    path.write_text(f"{head}{start}\n{note}{body.rstrip()}\n{end}{tail}")


# --- Flux Kustomizations -----------------------------------------------------


def flux_kustomizations():
    """Every Flux Kustomization, with the layer it belongs to.

    Layer is decided by where the *Kustomization* file lives, which is how Flux
    itself layers them: k8s/bootstrap is applied by hand, and each umbrella
    there points at a directory of Kustomizations under k8s/flux/.
    """
    rows = []
    for layer, prefix in (
        ("bootstrap", "k8s/bootstrap"),
        ("platform", "k8s/flux/platform"),
        ("apps", "k8s/flux/apps"),
    ):
        for f in sorted(yaml_files(prefix)):
            for d in load_all(f):
                if d.get("kind") != "Kustomization":
                    continue
                if not str(d.get("apiVersion", "")).startswith("kustomize.toolkit.fluxcd.io"):
                    continue
                spec = d.get("spec", {})
                rows.append(
                    {
                        "name": d["metadata"]["name"],
                        "layer": layer,
                        "path": spec.get("path", "").rstrip("/"),
                        "interval": spec.get("interval", "—"),
                        "prune": bool(spec.get("prune", False)),
                        "wait": bool(spec.get("wait", False)),
                        "timeout": spec.get("timeout"),
                        "depends_on": [x.get("name") for x in spec.get("dependsOn", []) or []],
                        "health_checks": len(spec.get("healthChecks", []) or []),
                        "suspend": bool(spec.get("suspend", False)),
                        "file": f,
                    }
                )
    return rows


def owner_of(repo_rel_path, kustomizations):
    """Name of the Flux Kustomization whose path contains the given file."""
    best = None
    for k in kustomizations:
        p = k["path"].lstrip("./")
        if repo_rel_path == p or repo_rel_path.startswith(p + "/"):
            if best is None or len(p) > len(best["path"]):
                best = k
    return best["name"] if best else None


def write_flux_kustomizations(rows):
    out = [BANNER, "# Flux Kustomizations { .quad-reference }\n\n"]
    out.append(
        "Every Flux `Kustomization` the cluster runs, grouped by the layer that applies\n"
        "it. For why the layers exist and what the prune and wait exceptions protect,\n"
        "see [how Flux is layered](../explanation/flux-layering.md).\n"
    )
    by_layer = {}
    for r in rows:
        by_layer.setdefault(r["layer"], []).append(r)

    no_prune = [r["name"] for r in rows if not r["prune"]]
    waits = [r["name"] for r in rows if r["wait"]]
    deps = [r["name"] for r in rows if r["depends_on"]]
    suspended = [r["name"] for r in rows if r["suspend"]]

    out.append("\n| | |\n| --- | --- |\n")
    out.append(
        f"| **Total** | {len(rows)} — "
        + ", ".join(f"{len(by_layer.get(l, []))} {l}" for l in ("bootstrap", "platform", "apps"))
        + " |\n"
    )
    out.append(f"| **`prune: false`** | {code_list(no_prune, 'none')} |\n")
    out.append(f"| **`wait: true`** | {code_list(waits, 'none')} |\n")
    out.append(f"| **Declare `dependsOn`** | {code_list(deps, 'none')} |\n")
    out.append(f"| **Suspended in git** | {code_list(suspended, 'none')} |\n")

    for layer, title in (
        ("bootstrap", "Bootstrap — applied once by hand"),
        ("platform", "Platform"),
        ("apps", "Apps"),
    ):
        out.append(f"\n## {title}\n\n")
        out.append("| Kustomization | Path | Interval | Prune | Wait | Depends on |\n")
        out.append("| --- | --- | --- | --- | --- | --- |\n")
        for r in sorted(by_layer.get(layer, []), key=lambda x: x["name"]):
            prune = "yes" if r["prune"] else "**no**"
            wait = "**yes**" if r["wait"] else "no"
            if r["wait"] and r["timeout"]:
                wait += f" ({r['timeout']})"
            out.append(
                f"| `{r['name']}` | {tree(r['path'])} | `{r['interval']}` | {prune} | {wait} | "
                f"{code_list(r['depends_on'])} |\n"
            )
    (DOCS / "flux-kustomizations.md").write_text("".join(out))


# --- Applications ------------------------------------------------------------


def hosts_from_values(doc):
    """Hostnames a Helm chart would render an Ingress for, read from values.

    Charts disagree on shape, so this walks every subtree under a key named
    `ingress` and accepts the three forms in use: `host: x`, `hosts: [x]`, and
    `hosts: [{host: x}]` or `[{name: x}]`. The class is `className` or
    `ingressClassName` on the same mapping, else the cluster default. Anything
    with `enabled: false` is skipped. Returned as (host, class, "values").
    """
    found = []

    def hosts_in(node):
        if not isinstance(node, dict) or node.get("enabled") is False:
            return
        cls = node.get("className") or node.get("ingressClassName") or "default class"
        names = []
        if isinstance(node.get("host"), str):
            names.append(node["host"])
        for h in node.get("hosts", []) or []:
            if isinstance(h, str):
                names.append(h)
            elif isinstance(h, dict):
                n = h.get("host") or h.get("name")
                if isinstance(n, str):
                    names.append(n)
        for n in names:
            found.append((n, cls, "values"))
        for k, v in node.items():
            if k in ("hosts", "tls", "annotations", "labels"):
                continue
            if isinstance(v, dict):
                hosts_in(v)

    def walk(node):
        if isinstance(node, dict):
            for k, v in node.items():
                if k == "ingress":
                    hosts_in(v)
                else:
                    walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)

    walk(doc)
    return found


def apps(kustomizations):
    """One row per directory under k8s/apps.

    Enumerated by directory, not by root kustomization.yaml: homer, paperless and
    dlna-local have none, because their Flux Kustomizations point at
    subdirectories instead.
    """
    by_app = {}
    for f in yaml_files("k8s/apps"):
        parts = f.relative_to(ROOT).parts
        if len(parts) < 4:
            continue
        by_app.setdefault(parts[2], []).append(f)

    rows = []
    for app in sorted(by_app):
        ns, ingresses = None, []
        for f in sorted(by_app[app]):
            for d in load_all(f):
                if d.get("kind") == "Namespace" and not ns:
                    ns = d.get("metadata", {}).get("name")
                if d.get("namespace") and not ns:
                    ns = d["namespace"]
                if d.get("kind") == "Ingress":
                    cls = d.get("spec", {}).get("ingressClassName", "?")
                    for rule in d.get("spec", {}).get("rules", []) or []:
                        if rule.get("host"):
                            ingresses.append((rule["host"], cls, "manifest"))
                elif not is_k8s_object(d):
                    ingresses.extend(hosts_from_values(d))
        owners = sorted(
            {
                k["name"]
                for k in kustomizations
                if k["path"] == f"./k8s/apps/{app}" or k["path"].startswith(f"./k8s/apps/{app}/")
            }
        )
        readme = ROOT / "k8s" / "apps" / app / "README.md"
        rows.append((app, ns, owners, sorted(set(ingresses)), readme if readme.exists() else None))
    return rows


def write_apps(rows):
    out = [BANNER, "# Applications { .quad-reference }\n\n"]
    out.append(
        "Every application under `k8s/apps/`, the namespace it renders into, the Flux\n"
        "Kustomization that applies it, and the hostnames it answers on. Where an app\n"
        "keeps a README next to its manifests, the app name links to it.\n"
    )
    out.append(
        "\n!!! note\n\n"
        "    Hostnames come from Ingress manifests and from the `ingress` section of\n"
        "    chart values; the latter are marked *values*. A host whose class reads\n"
        "    *default class* is rendered by a chart that sets no class and lands on\n"
        "    the cluster default — see [ingress classes](ingress.md).\n"
    )
    out.append("\n| App | Namespace | Flux Kustomization | Hostnames |")
    out.append("\n| --- | --- | --- | --- |\n")
    for app, ns, flux, ing, readme in rows:
        cells = []
        for h, c, src in ing:
            tag = f" ({c})" if src == "manifest" else f" ({c}, *values*)"
            cells.append(f"`{h}`{tag}")
        hosts = "<br>".join(cells) if cells else "—"
        name = f"[`{app}`]({REPO}/blob/master/{rel(readme)})" if readme else f"`{app}`"
        out.append(
            f"| {name} | `{ns or '—'}` | "
            f"{', '.join(f'`{f}`' for f in flux) or '**none**'} | {hosts} |\n"
        )
    out.append(f"\n{len(rows)} applications.\n")
    (DOCS / "apps.md").write_text("".join(out))


# --- Admission policies ------------------------------------------------------

POLICY_GROUPS = ("policies.kyverno.io", "kyverno.io")


def policies(kustomizations):
    """Every Kyverno policy anywhere under k8s/.

    Not just the kyverno component's own directory: the storage classes ship the
    policies that describe them (validate-roaming-volume-size lives with piraeus,
    mutate-nfs-pvc-alert-exclusion with csi-nfs), and cnpg-system ships a
    DeletingPolicy. A reader asking "what will admission do to my PVC" needs all
    of them in one place.
    """
    rows = []
    for f in sorted(yaml_files("k8s")):
        for d in load_all(f):
            api = str(d.get("apiVersion", ""))
            if not any(api.startswith(g) for g in POLICY_GROUPS):
                continue
            kind = d.get("kind", "")
            if not kind.endswith("Policy"):
                continue
            spec = d.get("spec", {})
            res, ops = set(), set()
            for rule in spec.get("matchConstraints", {}).get("resourceRules", []) or []:
                res.update(rule.get("resources", []) or [])
                ops.update(rule.get("operations", []) or [])
            if kind == "ValidatingPolicy":
                effect = ", ".join(spec.get("validationActions") or []) or "—"
            elif kind == "MutatingPolicy":
                effect = "Mutate"
            elif kind == "DeletingPolicy":
                effect = f"Delete on schedule `{spec.get('schedule', '?')}`"
            elif kind == "GeneratingPolicy":
                effect = "Generate"
            elif kind == "ClusterPolicy":
                effect = spec.get("validationFailureAction", "—")
            else:
                effect = "—"
            rows.append(
                {
                    "name": d["metadata"]["name"],
                    "kind": kind,
                    "resources": sorted(res),
                    "operations": sorted(ops),
                    "effect": effect,
                    "failure_policy": spec.get("failurePolicy"),
                    "scope": [
                        " ".join(str(c.get("expression", "")).split())
                        for c in spec.get("matchConditions", []) or []
                    ],
                    "conditions": [
                        c.get("name", "") for c in spec.get("conditions", []) or []
                    ],
                    "messages": [
                        " ".join(str(v.get("message", "")).split())
                        for v in spec.get("validations", []) or []
                        if v.get("message")
                    ],
                    "component": owner_of(rel(f), kustomizations) or "—",
                    "file": f,
                }
            )
    rows.sort(key=lambda r: r["name"])
    return rows


def write_policies(rows):
    out = [BANNER, "# Admission policies { .quad-reference }\n\n"]
    out.append(
        "Every Kyverno policy in the repository, wherever it lives: the kyverno\n"
        "component's own policies and the ones storage components ship to describe\n"
        "their classes. **Deny** blocks the apply; **Warn** records an audit warning\n"
        "and lets it through, so a warn-only rule is invisible until something goes\n"
        "wrong; **Mutate** changes the object on the way in; **Delete** runs on a\n"
        "schedule against objects that already exist.\n"
    )
    out.append("\n| Policy | Applies to | Effect | Shipped by |")
    out.append("\n| --- | --- | --- | --- |\n")
    for r in rows:
        anchor = r["name"].replace(".", "")
        out.append(
            f"| [`{r['name']}`](#{anchor}) | {code_list(r['resources'])} | "
            f"**{r['effect']}** | `{r['component']}` |\n"
        )
    for r in rows:
        out.append(f"\n## `{r['name']}`\n\n")
        out.append("| | |\n| --- | --- |\n")
        out.append(f"| **Kind** | `{r['kind']}` |\n")
        out.append(f"| **Applies to** | {code_list(r['resources'])} |\n")
        if r["operations"]:
            out.append(f"| **On** | {code_list(r['operations'])} |\n")
        out.append(f"| **Effect** | **{r['effect']}** |\n")
        if r["failure_policy"]:
            note = " — a policy error skips the rule silently" if r["failure_policy"] == "Ignore" else ""
            out.append(f"| **failurePolicy** | `{r['failure_policy']}`{note} |\n")
        if r["scope"]:
            out.append(
                "| **Only when** | " + "<br>".join(f"`{s}`" for s in r["scope"]) + " |\n"
            )
        out.append(f"| **Shipped by** | `{r['component']}` |\n")
        out.append(f"| **Source** | {blob(r['file'])} |\n")
        if r["messages"]:
            out.append("\nRules enforced:\n\n")
            for m in r["messages"]:
                out.append(f"- {m}\n")
        if r["conditions"]:
            out.append("\nDeletes only objects matching all of:\n\n")
            for c in r["conditions"]:
                out.append(f"- `{c}`\n")
    (DOCS / "admission-policies.md").write_text("".join(out))


# --- Helm releases -----------------------------------------------------------


def component_namespace(path, cache):
    """Namespace a manifest renders into: the nearest kustomization.yaml that
    sets `namespace:`, else a Namespace object in the same component tree."""
    d = path.parent
    while d != ROOT and len(d.relative_to(ROOT).parts) >= 3:
        if d in cache:
            return cache[d]
        k = d / "kustomization.yaml"
        if k.exists():
            for doc in load_all(k):
                if doc.get("namespace"):
                    cache[d] = doc["namespace"]
                    return doc["namespace"]
        for f in sorted(d.glob("*.yaml")):
            for doc in load_all(f):
                if doc.get("kind") == "Namespace":
                    cache[d] = doc["metadata"]["name"]
                    return cache[d]
        d = d.parent
    return None


def helm_repositories():
    repos = {}
    for f in yaml_files("k8s"):
        for d in load_all(f):
            if d.get("kind") == "HelmRepository":
                repos[d["metadata"]["name"]] = d.get("spec", {}).get("url", "")
    return repos


def helm_releases(kustomizations):
    repos = helm_repositories()
    rows, cache = [], {}
    for f in sorted(yaml_files("k8s")):
        for d in load_all(f):
            if d.get("kind") != "HelmRelease":
                continue
            if not str(d.get("apiVersion", "")).startswith("helm.toolkit.fluxcd.io"):
                continue
            spec = d.get("spec", {})
            chart_spec = spec.get("chart", {}).get("spec", {})
            chart_ref = spec.get("chartRef", {})
            chart = chart_spec.get("chart") or chart_ref.get("name") or "?"
            src_name = chart_spec.get("sourceRef", {}).get("name") or chart_ref.get("name")
            source = repos.get(src_name, src_name or "—")
            values = []
            for v in spec.get("valuesFrom", []) or []:
                values.append(f"{v.get('kind', '?')} `{v.get('name', '?')}`")
            if spec.get("values"):
                values.append("inline `spec.values`")
            rows.append(
                {
                    "name": spec.get("releaseName") or d["metadata"]["name"],
                    "namespace": d["metadata"].get("namespace") or component_namespace(f, cache) or "—",
                    "chart": chart,
                    "source": source,
                    "interval": spec.get("interval", "—"),
                    "values": "<br>".join(values) if values else "chart defaults",
                    "component": owner_of(rel(f), kustomizations) or "—",
                    "file": f,
                }
            )
    rows.sort(key=lambda r: (r["namespace"], r["name"]))
    return rows


def write_helm_releases(rows):
    out = [BANNER, "# Helm releases { .quad-reference }\n\n"]
    out.append(
        "Every `HelmRelease`, the chart it installs and where from, how often\n"
        "helm-controller re-checks it, and where its values come from. Chart versions\n"
        "are deliberately absent — Renovate moves them several times a week, and the\n"
        "linked manifest is where they live. For why values come from a ConfigMap\n"
        "and why the interval matters, see\n"
        "[why Helm values live in a file](../explanation/helm-values.md).\n"
    )
    charts = {}
    for r in rows:
        charts.setdefault(r["chart"], []).append(r["name"])
    intervals = sorted({str(r["interval"]) for r in rows})

    out.append("\n| | |\n| --- | --- |\n")
    out.append(f"| **Total** | {len(rows)} releases, {len(charts)} distinct charts |\n")
    out.append(f"| **Intervals in use** | {code_list(intervals)} |\n")
    multi = {c: n for c, n in charts.items() if len(n) > 1}
    if multi:
        out.append(
            "| **Charts used more than once** | "
            + ", ".join(f"`{c}` ×{len(n)}" for c, n in sorted(multi.items(), key=lambda x: -len(x[1])))
            + " |\n"
        )

    out.append("\n| Release | Namespace | Chart | Source | Interval | Values from | Component |\n")
    out.append("| --- | --- | --- | --- | --- | --- | --- |\n")
    for r in rows:
        name = f"[`{r['name']}`]({REPO}/blob/master/{rel(r['file'])})"
        out.append(
            f"| {name} | `{r['namespace']}` | `{r['chart']}` | `{r['source']}` | "
            f"`{r['interval']}` | {r['values']} | `{r['component']}` |\n"
        )
    (DOCS / "helm-releases.md").write_text("".join(out))


# --- Ingress: classes, issuers, external-dns (blocks in ingress.md) ----------


def sibling_chart(values_file):
    """Chart name of the HelmRelease that sits next to a values file."""
    for f in sorted(values_file.parent.glob("*.yaml")):
        for d in load_all(f):
            if d.get("kind") == "HelmRelease":
                spec = d.get("spec", {})
                return (
                    spec.get("chart", {}).get("spec", {}).get("chart")
                    or spec.get("chartRef", {}).get("name")
                    or "?"
                ), f
    return "?", None


def ingress_classes():
    """One row per IngressClass a network component's chart creates.

    Read from values rather than from IngressClass manifests because the classes
    here are chart-created: `ingressClass.name` in the Traefik and cloudflared
    values. The address is the Traefik LoadBalancer IP or the Cloudflare tunnel.
    """
    rows = []
    for f in sorted(yaml_files("k8s/platform/network")):
        for d in load_all(f):
            if is_k8s_object(d):
                continue
            ic = d.get("ingressClass")
            if not isinstance(ic, dict) or not ic.get("name") or ic.get("enabled") is False:
                continue
            chart, release = sibling_chart(f)
            lb = d.get("service", {}).get("spec", {}).get("loadBalancerIP")
            tunnel = d.get("cloudflare", {}).get("tunnelName")
            if lb:
                address = f"`{lb}`"
            elif tunnel:
                address = f"Cloudflare tunnel `{tunnel}`"
            else:
                address = "—"
            rows.append(
                {
                    "name": ic["name"],
                    "chart": chart,
                    "address": address,
                    "default": bool(ic.get("isDefaultClass", False)),
                    "file": f,
                }
            )
    rows.sort(key=lambda r: r["name"])
    return rows


def cluster_issuers():
    rows = []
    for f in sorted(yaml_files("k8s")):
        for d in load_all(f):
            if d.get("kind") != "ClusterIssuer":
                continue
            acme = d.get("spec", {}).get("acme", {})
            challenges = []
            for s in acme.get("solvers", []) or []:
                for kind in ("dns01", "http01"):
                    if kind in s:
                        provider = next(iter((s[kind] or {}).keys()), "")
                        label = "DNS-01" if kind == "dns01" else "HTTP-01"
                        challenges.append(f"{label} ({provider})" if provider else label)
            server = acme.get("server", "")
            if "acme-v02.api.letsencrypt.org" in server:
                server = "Let's Encrypt, production"
            elif "acme-staging" in server:
                server = "Let's Encrypt, **staging**"
            rows.append(
                {
                    "name": d["metadata"]["name"],
                    "challenges": challenges or ["—"],
                    "server": server or "—",
                    "file": f,
                }
            )
    rows.sort(key=lambda r: r["name"])
    return rows


def external_dns_settings():
    """The external-dns values that decide what gets published where."""
    files = [f for f in yaml_files("k8s/platform/network/external-dns") if f.name.startswith("values")]
    for f in files:
        for d in load_all(f):
            if is_k8s_object(d):
                continue
            provider = d.get("provider")
            if isinstance(provider, dict):
                provider = provider.get("name", "?")
            template = None
            for arg in d.get("extraArgs", []) or []:
                if isinstance(arg, str) and arg.startswith("--fqdn-template="):
                    # Helm-escaped in the values file: {{`{{`}}.Name{{`}}`}} -> {{.Name}}
                    template = arg.split("=", 1)[1].replace("{{`{{`}}", "{{").replace("{{`}}`}}", "}}")
            return {
                "provider": provider or "—",
                "domains": d.get("domainFilters", []) or [],
                "policy": d.get("policy", "—"),
                "registry": d.get("registry", "—"),
                "owner": d.get("txtOwnerId", "—"),
                "prefix": d.get("txtPrefix", "—"),
                "template": template,
                "file": f,
            }
    return None


def write_ingress_blocks():
    page = DOCS / "ingress.md"

    ic = ingress_classes()
    body = ["| Class | Controller chart | Address | Default class | Source |", "| --- | --- | --- | --- | --- |"]
    for r in ic:
        body.append(
            f"| `{r['name']}` | `{r['chart']}` | {r['address']} | "
            f"{'**yes**' if r['default'] else 'no'} | {blob(r['file'])} |"
        )
    write_block(page, "ingress-classes", "\n".join(body))

    ci = cluster_issuers()
    body = ["| Issuer | Challenge | ACME server | Source |", "| --- | --- | --- | --- |"]
    for r in ci:
        body.append(f"| `{r['name']}` | {', '.join(r['challenges'])} | {r['server']} | {blob(r['file'])} |")
    write_block(page, "cluster-issuers", "\n".join(body))

    ed = external_dns_settings()
    if ed is None:
        sys.exit("external-dns values not found")
    body = ["| Setting | Value |", "| --- | --- |"]
    body.append(f"| Provider | `{ed['provider']}` |")
    body.append(f"| Domains it will touch | {code_list(ed['domains'])} |")
    body.append(f"| Policy | `{ed['policy']}` |")
    body.append(f"| Ownership | `{ed['registry']}` registry, `txtOwnerId: {ed['owner']}`, `txtPrefix: {ed['prefix']}` |")
    if ed["template"]:
        body.append(f"| Fallback name for a Service with no host | `{ed['template']}` |")
    body.append(f"| Source | {blob(ed['file'])} |")
    write_block(page, "external-dns", "\n".join(body))
    return len(ic), len(ci)


# --- main --------------------------------------------------------------------


def main():
    if not DOCS.is_dir():
        sys.exit(f"{DOCS} does not exist")
    ks = flux_kustomizations()
    write_flux_kustomizations(ks)
    app_rows = apps(ks)
    write_apps(app_rows)
    pol = policies(ks)
    write_policies(pol)
    hr = helm_releases(ks)
    write_helm_releases(hr)
    n_classes, n_issuers = write_ingress_blocks()
    print(
        f"wrote flux-kustomizations.md ({len(ks)}), apps.md ({len(app_rows)}), "
        f"admission-policies.md ({len(pol)}), helm-releases.md ({len(hr)}), "
        f"ingress.md blocks ({n_classes} classes, {n_issuers} issuers)"
    )


if __name__ == "__main__":
    main()
