#!/usr/bin/env python3
"""Lint docs/ for the ways these pages have actually gone stale.

Two prior doc sets for this cluster died of staleness, not of missing content.
This checks the mechanical part of that: a page that names something the
repository no longer has, or that will drift the next time the manifests move.

Errors (exit 1):

  link      a relative Markdown link to a page or anchor file that does not exist
  nav       a page under docs/ that zensical.toml does not list, or a nav entry
            pointing at a file that is not there
  path      a backticked repository path (k8s/..., hack/..., docs/..., .claude/...,
            .github/..., metal/...) that does not exist
  namespace `kubectl -n <ns>` naming a namespace no manifest declares
  policy    a Kyverno policy name no manifest declares

Warnings (reported, never fatal; GitHub annotations under Actions):

  image     a container image tag quoted in the docs that no manifest carries
            -- Renovate bumped the cluster and left the how-to behind
  count     a number of things in prose ("24 components", "all 47") -- these are
            derivable and belong in a generated reference page, linked
  temporal  "currently", "planned", "not yet", "today" -- true on the day it
            was written, and nothing will revisit it

Placeholders (`<app>`, `myapp`, `whoami`, `…`) are skipped everywhere.

Usage: hack/lint-docs.py [--strict]     (--strict makes warnings fatal)
"""

import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
NAV = ROOT / "zensical.toml"

PLACEHOLDER = re.compile(r"<[^>]+>|…|\.\.\.|\bmyapp\b|\bwhoami\b|\bexample\b|\*|\$\{?\w+")
GENERATED = "Generated by hack/generate-docs-reference.py"

REPO_PATH = re.compile(r"`((?:k8s|hack|docs|metal|\.claude|\.github)/[A-Za-z0-9_./<>*…-]*)`")
MD_LINK = re.compile(r"\[[^\]]*\]\(([^)\s]+)\)")
MD_REF = re.compile(r"^\[[^\]]+\]:\s+(\S+)", re.M)
KUBECTL_NS = re.compile(r"kubectl\s+(?:-n|--namespace)[= ]([A-Za-z0-9<>_.-]+)")
POLICY_NAME = re.compile(r"`((?:validate|mutate|require|cleanup|generate)-[a-z0-9-]+)`")
IMAGE = re.compile(
    r"(?<![\w/.-])((?:[a-z0-9.-]+\.[a-z]{2,}/)?[a-z0-9._-]+(?:/[a-z0-9._-]+)+):(v?\d[\w.+-]*)"
)
COUNT_WORDS = (
    r"\b(?:\d{1,3}|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|all \d{1,3})"
    r"(?: of (?:the )?\d{1,3})? "
    r"(?:apps|applications|components|Kustomizations|HelmReleases|releases|databases|"
    r"clusters|policies|ExternalSecrets|PrometheusRule(?:s)? files|rules|directories|"
    r"objects|hostnames|namespaces|exceptions)\b"
)
COUNT = re.compile(COUNT_WORDS)
TEMPORAL = re.compile(
    r"\b(?:currently|at the moment|right now|today|not yet|planned|for now|"
    r"still (?:serving|being|exists)|open item|work in progress|interim)\b",
    re.I,
)

errors, warnings = [], []


def tracked(prefix):
    out = subprocess.run(
        ["git", "-C", str(ROOT), "ls-files", prefix],
        capture_output=True, text=True, check=True,
    ).stdout.split()
    return [ROOT / p for p in out]


def err(path, line, check, msg):
    errors.append((path, line, check, msg))


def warn(path, line, check, msg):
    warnings.append((path, line, check, msg))


def strip_code_fences(text):
    """Return (prose_lines, all_lines): prose has fenced code blanked so image
    and count checks only fire on sentences, not on YAML the reader will paste."""
    prose, in_fence = [], False
    for line in text.splitlines():
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            prose.append("")
            continue
        prose.append("" if in_fence else line)
    return prose, text.splitlines()


# --- facts from the manifests ------------------------------------------------


def manifest_namespaces():
    names = set()
    for f in tracked("k8s"):
        if f.suffix not in (".yaml", ".yml"):
            continue
        text = f.read_text(errors="ignore")
        if f.name == "kustomization.yaml":
            m = re.search(r"^namespace:\s*(\S+)", text, re.M)
            if m:
                names.add(m.group(1))
        for m in re.finditer(r"^kind:\s*Namespace\s*\n(?:.*\n)*?\s+name:\s*(\S+)", text, re.M):
            names.add(m.group(1))
    # Namespaces created by charts or by k3s itself rather than by a manifest here.
    names |= {"kube-system", "default", "flux-system", "kube-public", "kube-node-lease"}
    return names


def manifest_policies():
    names = set()
    for f in tracked("k8s"):
        if f.suffix not in (".yaml", ".yml"):
            continue
        text = f.read_text(errors="ignore")
        if "kyverno.io" not in text:
            continue
        for m in re.finditer(r"^kind:\s*\w+Policy\s*\nmetadata:\s*\n(?:\s+#.*\n)*\s+name:\s*(\S+)", text, re.M):
            names.add(m.group(1))
    return names


def manifest_image_tags():
    """image repo -> set of tags anywhere under k8s/ (manifests and values)."""
    tags = {}
    for f in tracked("k8s"):
        if f.suffix not in (".yaml", ".yml"):
            continue
        for m in IMAGE.finditer(f.read_text(errors="ignore")):
            tags.setdefault(m.group(1), set()).add(m.group(2))
    return tags


# --- checks -------------------------------------------------------------------


def check_nav(pages):
    if not NAV.exists():
        return
    listed = set(re.findall(r'"([^"]+\.md)"', NAV.read_text()))
    for entry in sorted(listed):
        if not (DOCS / entry).exists():
            err(NAV, 0, "nav", f"nav entry {entry!r} does not exist under docs/")
    for p in pages:
        r = str(p.relative_to(DOCS))
        if r not in listed:
            err(p, 0, "nav", "page is not in the zensical.toml nav (orphan)")


def check_page(path, ns_set, policy_set, image_tags):
    text = path.read_text()
    generated = GENERATED in text
    prose, lines = strip_code_fences(text)

    for i, line in enumerate(lines, 1):
        for target in MD_LINK.findall(line) + MD_REF.findall(line):
            if target.startswith(("http://", "https://", "mailto:", "#")):
                continue
            file_part = target.split("#", 1)[0]
            if not file_part:
                continue
            if not (path.parent / file_part).resolve().exists():
                err(path, i, "link", f"broken relative link {target!r}")

        for m in REPO_PATH.finditer(line):
            p = m.group(1)
            if PLACEHOLDER.search(p):
                continue
            if not (ROOT / p.rstrip("/")).exists():
                err(path, i, "path", f"`{p}` does not exist in the repository")

        for m in KUBECTL_NS.finditer(line):
            ns = m.group(1)
            if PLACEHOLDER.search(ns):
                continue
            if ns not in ns_set:
                err(path, i, "namespace", f"`kubectl -n {ns}`: no manifest declares namespace {ns!r}")

        for m in POLICY_NAME.finditer(line):
            if m.group(1) not in policy_set:
                err(path, i, "policy", f"policy `{m.group(1)}` is not declared by any manifest")

    if generated:
        return

    for i, line in enumerate(lines, 1):
        for m in IMAGE.finditer(line):
            repo, tag = m.group(1), m.group(2)
            if repo not in image_tags:
                continue  # not something the cluster runs; nothing to drift from
            if tag not in image_tags[repo]:
                warn(
                    path, i, "image",
                    f"{repo}:{tag} — manifests carry {', '.join(sorted(image_tags[repo]))}",
                )

    for i, line in enumerate(prose, 1):
        if line.lstrip().startswith("|"):
            continue  # tables are content, not prose
        for m in COUNT.finditer(line):
            warn(path, i, "count", f"{m.group(0)!r} is a count in prose; link a generated reference instead")
        for m in TEMPORAL.finditer(line):
            warn(path, i, "temporal", f"{m.group(0)!r} dates the sentence; state the fact or remove it")


def report(items, level):
    gha = os.environ.get("GITHUB_ACTIONS") == "true"
    for path, line, check, msg in items:
        rel = path.relative_to(ROOT) if path.is_absolute() else path
        print(f"{rel}:{line}: {level} [{check}] {msg}")
        if gha:
            print(f"::{level} file={rel},line={max(line, 1)},title=docs {check}::{msg}")


def main():
    strict = "--strict" in sys.argv
    pages = sorted(p for p in DOCS.rglob("*.md"))
    ns_set = manifest_namespaces()
    policy_set = manifest_policies()
    image_tags = manifest_image_tags()

    check_nav(pages)
    for p in pages:
        check_page(p, ns_set, policy_set, image_tags)

    report(errors, "error")
    report(warnings, "warning")
    print(f"\n{len(pages)} pages, {len(errors)} errors, {len(warnings)} warnings")
    if errors or (strict and warnings):
        sys.exit(1)


if __name__ == "__main__":
    main()
