#!/bin/bash

# Vendors the policies.kyverno.io CRDs into k8s/crds/kyverno/, one file per
# CRD, rendered from upstream's kyverno-api chart at the version the kyverno
# chart depends on.
#
# They are files rather than a HelmRelease because a standalone kyverno-api
# release cannot be stored. Helm keeps a release's own template files and its
# rendered manifest in one Secret; for this chart both are the same eleven
# CRDs, 2.4 MB of schema twice over, and gzipped that is more than the 1 MiB a
# Secret may hold. Inside the kyverno chart the same CRDs are a dependency's
# templates, which Helm does not store, so that release fits. No ownership or
# ordering setting changes the arithmetic.
#
# The kyverno chart's dependency list is the authority for the version, so
# this asks it rather than keeping a copy of the number. `make
# validate-kyverno-crds` reruns this and fails when the tree changes: a
# kyverno bump that moves the dependency has to land together with a rerun.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit 1

CONTROLLERS=k8s/platform/security/kyverno/controllers/release.yaml
REPOSITORY=k8s/platform/security/kyverno/controllers/repository.yaml
OUT=k8s/crds/kyverno

kyverno_version="$(yq '.spec.chart.spec.version' "$CONTROLLERS")"
kyverno_repo="$(yq 'select(.kind == "HelmRepository") | .spec.url' "$REPOSITORY")"

dependency="$(helm show chart kyverno --repo "$kyverno_repo" --version "$kyverno_version" \
  | yq '.dependencies[] | select(.name == "kyverno-api")')"
api_version="$(yq '.version' <<<"$dependency")"
api_repo="$(yq '.repository' <<<"$dependency")"

if [[ -z "$api_version" || "$api_version" == "null" ]]; then
  echo "kyverno $kyverno_version does not depend on kyverno-api any more." >&2
  echo "If upstream folded the CRDs back in, $OUT and the post-renderer in" >&2
  echo "$CONTROLLERS both need revisiting." >&2
  exit 1
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# Default values render empty label and annotation maps; drop them so the
# files say only what the chart says.
helm template kyverno-api kyverno-api --repo "$api_repo" --version "$api_version" \
  | yq 'del(.metadata.labels | select(length == 0)) | del(.metadata.annotations | select(length == 0))' \
  > "$work/all.yaml"

# yq names each file by the expression verbatim, so the extension is ours.
mkdir -p "$work/split"
(cd "$work/split" && yq -s '.metadata.name + ".yaml"' ../all.yaml)

mkdir -p "$OUT"
rm -f "$OUT"/*.yaml
header="# Generated by hack/vendor-kyverno-crds.sh from kyverno-api $api_version, the dependency of kyverno $kyverno_version. Do not edit; run make vendor-kyverno-crds."
count=0
for f in "$work"/split/*.yaml; do
  { echo "$header"; cat "$f"; } > "$OUT/$(basename "$f")"
  count=$((count + 1))
done

echo "vendored $count CRDs from kyverno-api $api_version, the dependency of kyverno $kyverno_version"
