apiVersion: homer.bananaops.io/v1alpha1
kind: HomerServices
metadata:
  name: grafana
spec:
  groups:
    - name: Administration
      icon: "fa fa-user-shield"
      items:
        - name: Grafana
          url: "https://grafana.krupa.net.pl"
          logo: "https://grafana.com/static/img/logos/grafana_logo_swirl-events.svg"
