apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vod-tv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Ti
  storageClassName: manual
  volumeName: vod-tv
