apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vod-movies
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  storageClassName: manual
  volumeName: vod-movies
