apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vod-downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: manual
  volumeName: vod-downloads
