apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: postgres
  name: postgres
spec:
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: backblaze
  #bootstrap:
  #  initdb:
  #    database: atuin
  #    owner: atuin
  #    secret:
  #      name: postgres-user
  #bootstrap:
  #  recovery:
  #    source: postgres
  #    database: atuin
  #    owner: atuin
  #    secret:
  #      name: postgres-user
  imageName: ghcr.io/cloudnative-pg/postgresql:16.11
  instances: 2
  monitoring:
    enablePodMonitor: true
  resources:
    limits:
      cpu: 400m
      memory: 420Mi
    requests:
      cpu: 130m
      memory: 300Mi
  storage:
    size: 7Gi
    storageClass: lvm-thin
  superuserSecret:
    name: postgres-admin
