apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - require-resource-requests.yaml
  - validate-pdb-drain-safety.yaml
  - validate-helm-chart-version.yaml
  - validate-ingress-contract.yaml
  - validate-roaming-volume-size.yaml
