apiVersion: v1
kind: Service
metadata:
  name: litellm
  labels:
    app.kubernetes.io/name: litellm
spec:
  ports:
    - name: http
      port: 4000
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: litellm
