database: pocketid
owner: pocketid

cluster:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 3
  storage:
    size: 9Gi
  resources:
    limits:
      cpu: 400m
      memory: 420Mi
    requests:
      cpu: 130m
      memory: 300Mi

backup:
  schedule: "0 17 23 * * *"
  objectStore:
    retentionPolicy: 30d
    # Not the namespace name.
    pathSuffix: pocketid

externalSecrets:
  admin:
    remoteKey: POCKET_ID_DB_ADMIN_PASS
  user:
    remoteKey: POCKET_ID_DB_PASS
