apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: kubelet-runtime-errors
spec:
  description: ""
  alerting:
    name: KubeletRuntimeBudgetBurn
    absentName: KubeletRuntimeMetricAbsent
    severities:
      fastBurn: info
      mediumBurn: info
      slowBurn: none
      longTermBurn: none
      absent: warning
  indicator:
    ratio:
      errors:
        metric: kubelet_runtime_operations_errors_total{job="kubelet"}
      total:
        metric: kubelet_runtime_operations_total{job="kubelet"}
  target: "99"
  window: 7d