apiVersion: homer.bananaops.io/v1alpha1
kind: HomerServices
metadata:
  name: prowlarr
spec:
  groups:
    - name: Multimedia
      icon: "fa fa-tv"
      items:
        - name: Prowlarr
          url: "https://prowlarr.ankhmorpork.thaum.xyz"
          subtitle: "Indexer/proxy management"
          logo: "https://cdn.jsdelivr.net/npm/@loganmarchione/homelab-svg-assets@latest/assets/prowlarr.svg"
          tag: local
          tagstyle: "is-success"
