apiVersion: homer.bananaops.io/v1alpha1
kind: HomerServices
metadata:
  name: karakeep
spec:
  groups:
    - name: Ankh Cloud
      icon: "fa fa-cloud"
      items:
        - name: Karakeep
          url: "https://keep.krupa.net.pl"
          subtitle: "Bookmarks hoarder"
          logo: "https://avatars.githubusercontent.com/u/202258986?s=60&v=4"
