apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./k8s/apps/grafana
  prune: true
  sourceRef:
    kind: GitRepository
    name: ankhmorpork
