apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mended-drum
  namespace: flux-system
spec:
  suspend: true # FIXME(paulfantom): Temporary measure to prevent re-sync of all apps
  interval: 15m0s
  path: ./k8s/apps/mended-drum
  prune: true
  sourceRef:
    kind: GitRepository
    name: ankhmorpork
