apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: unifi
  namespace: flux-system
spec:
  suspend: true # FIXME(paulfantom): Temporary measure to prevent re-sync of all apps
  interval: 120m0s
  path: ./k8s/apps/unifi
  prune: true
  sourceRef:
    kind: GitRepository
    name: ankhmorpork
