apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 120Gi
  storageClassName: manual
  volumeName: downloads
