apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config.yaml
  - deployment.yaml
  - ingress.yaml
  - podmonitor.yaml
  - pvc-config.yaml
  - service.yaml
  - vpn-credentials.yaml
