apiVersion: v1
kind: Namespace
metadata:
  name: mealie
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    flux.rbac.thaum.xyz/role: cluster-admin
    group.rbac.thaum.xyz/appadmin: edit
    pod-security.kubernetes.io/enforce: baseline
