apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-repo-credentials
spec:
  data:
  - remoteRef:
      key: VELERO_REPO_PASSWORD
    secretKey: repository-password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
