apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mended-drum-tools-secrets
  labels:
    app.kubernetes.io/name: mended-drum-tools
spec:
  data:
    - remoteRef:
        key: MENDED_DRUM_MEALIE_TOKEN
      secretKey: MEALIE_API_TOKEN
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: mended-drum-tools-secrets
