apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mended-drum-tools-data
  labels:
    app.kubernetes.io/name: mended-drum-tools
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
