apiVersion: v1
kind: Service
metadata:
  name: mended-drum-tools
  labels:
    app.kubernetes.io/name: mended-drum-tools
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: mended-drum-tools
