apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - oidc-secret.yaml
  - pvc.yaml
  - service.yaml
  - ingress.yaml
  - ingress-cloudflare.yaml
  - deployment.yaml
