apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  labels:
    app.kubernetes.io/name: open-webui
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
