apiVersion: homer.bananaops.io/v1alpha1
kind: HomerServices
metadata:
  name: mealie
spec:
  groups:
    - name: Ankh Cloud
      icon: "fa fa-cloud"
      items:
        - name: Mealie
          url: "https://recipes.krupa.net.pl"
          subtitle: "Our recipes"
          logo: "https://cdn.jsdelivr.net/npm/@loganmarchione/homelab-svg-assets@latest/assets/mealie.svg"
