apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-tv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Ti
  storageClassName: manual
  volumeName: plex-tv
