apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vod-vpn-creds
spec:
  data:
    - remoteRef:
        key: VPN_USERNAME
      secretKey: OPENVPN_USER
    - remoteRef:
        key: VPN_PASSWORD
      secretKey: OPENVPN_PASSWORD
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: vod-vpn-creds
