apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vod-arr
resources:
  - namespace.yaml
  - shared/
  - prowlarr/
  - prowlarrdb/
  - radarr/
  - radarrdb/
  - sonarr/
  - sonarrdb/
  - bazarr/
  - qbittorrent/
  - seerr/
  - flaresolverr/
  - cleanuparr/
  - recyclarr/
