apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - release.yaml
  - library-old-pv.yaml
  - library-old-pvc.yaml
  - library-pv.yaml
  - library-pvc.yaml
  - server-pdb.yaml
  - ingress-cloudflare.yaml
  - slo-probe-success.yaml
configMapGenerator:
  - name: values-immich
    files:
      - values.yaml=values.yaml
# Stable name; see docs/explanation/helm-values.md.
generatorOptions:
  disableNameSuffixHash: true
  labels:
    reconcile.fluxcd.io/watch: Enabled
