apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: longhorn-r2
