apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-api-key
spec:
  data:
    - remoteRef:
        key: PROWLARR_API_KEY
      secretKey: apiKey
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: prowlarr-api-key
