apiVersion: homer.bananaops.io/v1alpha1
kind: HomerServices
metadata:
  name: litellm
spec:
  groups:
    - name: Administration
      icon: "fa fa-user-shield"
      items:
        - name: Litellm
          url: "https://ai-gateway.krupa.net.pl"
          logo: "https://cdn.jsdelivr.net/npm/@loganmarchione/homelab-svg-assets@latest/assets/openai-white.svg"
