apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
  namespace: dlna-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: piraeus-r2
