apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4000Gi
  storageClassName: manual
  volumeName: photos
