apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8up
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./k8s/platform/storage/k8up
  prune: true
  sourceRef:
    kind: GitRepository
    name: ankhmorpork
