apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./k8s/platform/security/kyverno
  prune: true
  wait: true
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: ankhmorpork
